[workspace]
members = [
    "interval-core",
    "interval-smf",
    "interval-rt",
    "interval-cli",
]
resolver = "2"

[workspace.package]
version = "0.10.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/hiddenmountain/Interval"
rust-version = "1.87"
authors = ["Hidden Mountain srls"]
